name: HackerOne bot

on:
    push:
        branches:
            - master
    workflow_dispatch: # 手动触发
    schedule:
        - cron: '30 9 * * *'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
              with:
                  ref: 'main'
            - name: Use Python
              uses: actions/setup-python@v1
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -U requests
            - name: Run app
              run: |
                python hackerone.py
              env:
                DINGTALK_TOKEN: ${{ secrets.DINGTALK_TOKEN }}
